services:
  api:
    build : 
      context: ..
      dockerfile: .docker/api/Dockerfile
    container_name: ${PROJECT}_api
    develop:
      watch:
        - action: sync+restart
          path: ./api/conf-test-restart
          target: /etc/conf-test-restart
    volumes:
    - ../api:/var/www/html
    - ./api/apache2/sites-enabled:/etc/apache2/sites-enabled
    depends_on:
      db :
        condition: service_healthy
    ports:
      - 8080:80

  app:
    build:
      context: ..
      dockerfile: .docker/app/Dockerfile
    container_name: ${PROJECT}_app
    volumes:
      - ../app:/var/www/html
    ports:
      - 4200:4200

  db:
    image: mariadb:11.4.2
    container_name: ${PROJECT}_db
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  mailpit:
    image: axllent/mailpit
    container_name: ${PROJECT}_mailpit
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  db-data: {}
